[2024-04-25T06:21:56.756+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-25T06:21:56.773+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio_s3_v02.sensor_minio_s3 scheduled__2023-03-06T00:00:00+00:00 [queued]>
[2024-04-25T06:21:56.793+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio_s3_v02.sensor_minio_s3 scheduled__2023-03-06T00:00:00+00:00 [queued]>
[2024-04-25T06:21:56.803+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-25T06:21:56.826+0000] {taskinstance.py:2327} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2023-03-06 00:00:00+00:00
[2024-04-25T06:21:56.843+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=12526) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-25T06:21:56.844+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio_s3_v02', 'sensor_minio_s3', 'scheduled__2023-03-06T00:00:00+00:00', '--job-id', '2266', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio_s3.py', '--cfg-path', '/tmp/tmpi6dwq11j']
[2024-04-25T06:21:56.853+0000] {standard_task_runner.py:63} INFO - Started process 12534 to run task
[2024-04-25T06:21:56.853+0000] {standard_task_runner.py:91} INFO - Job 2266: Subtask sensor_minio_s3
[2024-04-25T06:21:56.915+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_minio_s3_v02.sensor_minio_s3 scheduled__2023-03-06T00:00:00+00:00 [running]> on host a55babecb56c
[2024-04-25T06:21:57.001+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='coder2j' AIRFLOW_CTX_DAG_ID='dag_with_minio_s3_v02' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-03-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-06T00:00:00+00:00'
[2024-04-25T06:21:57.004+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-25T06:21:57.032+0000] {baseoperator.py:399} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-04-25T06:21:57.041+0000] {s3.py:110} INFO - Poking for key : s3://***/data.csv
[2024-04-25T06:21:57.065+0000] {base.py:84} INFO - Using connection ID 'minio_conn' for task execution.
[2024-04-25T06:21:57.069+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from extra.
[2024-04-25T06:21:57.074+0000] {logging_mixin.py:188} WARNING - <string>:9 AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
[2024-04-25T06:21:57.228+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-04-25T06:21:57.230+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-25T06:21:57.238+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_with_minio_s3_v02, task_id=sensor_minio_s3, execution_date=20230306T000000, start_date=20240425T062156, end_date=20240425T062157
[2024-04-25T06:21:57.278+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-25T06:21:57.313+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-25T06:21:57.315+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
